export const TOGGLE_GEOFENCE_MODAL = 'TOGGLE_GEOFENCE_MODAL';
export const GOOGLE_IS_INITALIZED = 'GOOGLE_IS_INITALIZED';
export const FETCH_DEVICES_DATA = 'FETCH_DEVICES_DATA';
export const DRAWING_GEOFENCES = 'DRAWING_GEOFENCES';
export const DREW_GEOFENCES = 'DREW_GEOFENCES';
export const RESET_DREW_GEOFENCES = 'RESET_DREW_GEOFENCES';
export const DELETE_CURRENT_GEOFENCES = 'DELETE_CURRENT_GEOFENCES';
export const SAVE_CURRENT_GEOFENCES = 'SAVE_CURRENT_GEOFENCES';
export const TOGGLE_SAVE_GEOFENCE_DIALOG = 'TOGGLE_SAVE_GEOFENCE_DIALOG';
export const SAVE_GEOFENCE_NAME = 'SAVE_GEOFENCE_NAME';
export const SAVE_GEOFENCE_PATH = 'SAVE_GEOFENCE_PATH';
export const TOGGLE_GEOFENCE_ASSIGNMENT_DIALOG = 'TOGGLE_GEOFENCE_ASSIGNMENT_DIALOG';
export const FETCH_GEOFENCES = 'FETCH_GEOFENCES';
export const FETCH_DEVICES_IN_CURRENT_GEOFENCE = 'FETCH_DEVICES_IN_CURRENT_GEOFENCE';
export const FETCH_SEARCH_DEVICES = 'FETCH_SEARCH_DEVICES';
export const ADD_DEVICES_TO_A_GEOFENCE = 'ADD_DEVICES_TO_A_GEOFENCE';
export const DELETE_TEXT_GEOFENCE_ASSIGNMENT_DIALOG = 'DELETE_TEXT_GEOFENCE_ASSIGNMENT_DIALOG';
export const KEY_DOWN_INPUT_GEOFENCE_ASSIGNMENT_DIALOG = 'KEY_DOWN_INPUT_GEOFENCE_ASSIGNMENT_DIALOG';
export const CHANGE_INPUT_GEOFENCE_ASSIGNMENT_DIALOG = 'CHANGE_INPUT_GEOFENCE_ASSIGNMENT_DIALOG';
export const CHANGE_DEVICES_TO_ADD_GEOFENCE_ASSIGNMENT_DIALOG = 'CHANGE_DEVICES_TO_ADD_GEOFENCE_ASSIGNMENT_DIALOG';
export const DELETE_DEVICES_TO_ADD_GEOFENCE_ASSIGNMENT_DIALOG = 'DELETE_DEVICES_TO_ADD_GEOFENCE_ASSIGNMENT_DIALOG';
export const RADIO_BUTTON_CHANGE_GEOFENCE_ASSIGNMENT_DIALOG = 'RADIO_BUTTON_CHANGE_GEOFENCE_ASSIGNMENT_DIALOG';
export const TOGGLE_DEVICES_COMPONENT_ASSIGNMENT_DIALOG = 'TOGGLE_DEVICES_COMPONENT_ASSIGNMENT_DIALOG';


