export const TOGGLE_GEOFENCE_MODAL = 'TOGGLE_GEOFENCE_MODAL';
export const GOOGLE_IS_INITALIZED = 'GOOGLE_IS_INITALIZED';
export const GOOGLE_IS_READY = 'GOOGLE_IS_READY';
export const FETCH_DEVICES_DATA = 'FETCH_DEVICES_DATA';
